// <auto-generated />
using BitirmeProject.StorageService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace StorageService.Infrastructure.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20260326193000_TemporaryUploadWorkflow")]
    partial class TemporaryUploadWorkflow
    {
    }
}
