// <auto-generated />
using BitirmeProject.SprintService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SprintService.Infrastructure.Migrations
{
    [DbContext(typeof(SprintDbContext))]
    [Migration("20260328010000_UpdateOutboxSchema")]
    partial class UpdateOutboxSchema
    {
    }
}
