// <auto-generated />
using BitirmeProject.IssueService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IssueService.Infrastructure.Migrations
{
    [DbContext(typeof(IssueDbContext))]
    [Migration("20260328010000_UpdateOutboxSchema")]
    partial class UpdateOutboxSchema
    {
    }
}
