// <auto-generated />
using BitirmeProject.IssueService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IssueService.Infrastructure.Migrations
{
    [DbContext(typeof(IssueDbContext))]
    [Migration("20260326210000_AddAttachmentUniqueIndex")]
    partial class AddAttachmentUniqueIndex
    {
    }
}
